const A1QuizData = [

{q:"Which connector type is most commonly used on modern Android smartphones today?", options:["Micro-USB","USB-C","Lightning","Mini-USB"], correct:"USB-C"},
{q:"Which connector was commonly used on Apple iPhones before USB-C adoption occurred?", options:["USB-C","Micro-USB","Lightning","Thunderbolt"], correct:"Lightning"},
{q:"What is the primary purpose of a SIM card in mobile devices today?", options:["Store applications","Identify subscriber to network","Increase storage capacity","Provide Wi-Fi access"], correct:"Identify subscriber to network"},
{q:"What functionality is disabled when airplane mode is enabled on a smartphone device?", options:["Only Wi-Fi","Only Bluetooth","All wireless radios","GPS only"], correct:"All wireless radios"},
{q:"What is the main purpose of tethering on a mobile device connection?", options:["Charging devices","Sharing internet connection","Encrypting files","Transferring contacts"], correct:"Sharing internet connection"},
{q:"What is the primary function of GPS in modern mobile devices today?", options:["Internet access","Location tracking","File storage","Encryption"], correct:"Location tracking"},
{q:"Which authentication method uses fingerprint or facial recognition on mobile devices?", options:["PIN authentication","Password authentication","Biometric authentication","Token authentication"], correct:"Biometric authentication"},
{q:"What is the purpose of a mobile hotspot feature on smartphones today?", options:["Bluetooth pairing","Sharing internet connection","Local file storage","NFC communication"], correct:"Sharing internet connection"},
{q:"What type of communication does NFC enable between nearby mobile devices today?", options:["Long-range networking","Close-range communication","Wi-Fi encryption","GPS tracking"], correct:"Close-range communication"},
{q:"Which internal sensor is responsible for automatic screen rotation on smartphones today?", options:["GPS sensor","Accelerometer","Camera sensor","Microphone"], correct:"Accelerometer"},
{q:"What is the purpose of remote wipe functionality on mobile devices today?", options:["Restart device","Erase data remotely","Update operating system","Lock screen"], correct:"Erase data remotely"},
{q:"What is mobile device encryption primarily used for on smartphones today?", options:["Increase speed","Protect stored data","Improve battery life","Boost signal"], correct:"Protect stored data"},
{q:"What does a passcode lock provide on a mobile device for security?", options:["Network access","Device security","Storage expansion","Application updates"], correct:"Device security"},
{q:"What is Bluetooth pairing used for between two mobile devices today?", options:["Charging connection","Trusted device connection","Wi-Fi sharing","Data encryption"], correct:"Trusted device connection"},
{q:"What does a gyroscope sensor help detect in a mobile device system?", options:["Location","Orientation and rotation","Temperature","Signal strength"], correct:"Orientation and rotation"},
{q:"What does an accelerometer measure within a mobile device system?", options:["Speed changes","Temperature","Signal strength","Storage space"], correct:"Speed changes"},
{q:"What is a mobile operating system update used for regularly?", options:["Hardware replacement","Software improvements and fixes","File deletion","Battery replacement"], correct:"Software improvements and fixes"},
{q:"What is a PRL update used for on mobile carrier networks?", options:["App update","Roaming list update","Security patch","OS upgrade"], correct:"Roaming list update"},
{q:"What is sideloading applications onto a mobile device typically referring to?", options:["Installing apps outside official store","Deleting apps","Updating system","Encrypting data"], correct:"Installing apps outside official store"},
{q:"What is application sandboxing used for on mobile devices today?", options:["Isolate applications","Encrypt files","Share data","Boost performance"], correct:"Isolate applications"},
{q:"What is OLED display technology primarily known for in mobile devices?", options:["Requires backlight","Self-lit pixels","Lower contrast","Slower response"], correct:"Self-lit pixels"},
{q:"What is screen burn-in typically referring to on mobile displays?", options:["Temporary glitch","Permanent image retention","Low brightness","Screen flicker"], correct:"Permanent image retention"},
{q:"What is mobile data roaming used for when traveling outside local areas?", options:["Local networking","Use external carrier networks","Wi-Fi connection","Bluetooth pairing"], correct:"Use external carrier networks"},
{q:"What is a VPN used for on a mobile device connection?", options:["Increase speed","Secure connection","Add storage","Improve battery"], correct:"Secure connection"},
{q:"What is multi-factor authentication used for in mobile device security today?", options:["Multiple passwords","Multiple verification methods","Storage expansion","Faster login"], correct:"Multiple verification methods"},
{q:"What is a common cause of poor cellular signal reception indoors?", options:["Full storage","Physical obstructions","Too many apps","Low brightness"], correct:"Physical obstructions"},
{q:"What is the purpose of auto-lock settings on mobile devices today?", options:["Save battery and secure device","Increase speed","Improve signal","Delete files"], correct:"Save battery and secure device"},
{q:"What is the typical Bluetooth range for most mobile devices today?", options:["1 meter","10 meters","100 meters","1 kilometer"], correct:"10 meters"},
{q:"What is a factory reset used for on mobile devices today?", options:["Update OS","Restore default settings","Delete apps only","Lock system"], correct:"Restore default settings"},
{q:"What is auto-brightness feature used for on mobile device displays today?", options:["Increase speed","Adjust brightness automatically","Save storage","Boost signal"], correct:"Adjust brightness automatically"},
{q:"What is a common cause of rapid battery drain on mobile devices today?", options:["Airplane mode","Background applications","Low brightness","Disabled Wi-Fi"], correct:"Background applications"},
{q:"What is mobile device synchronization used for between multiple devices today?", options:["Charging","Sync data across devices","Deleting data","Locking apps"], correct:"Sync data across devices"},
{q:"What is a mobile configuration profile used for in enterprise environments?", options:["Hardware component","Configuration settings","Application store","Storage type"], correct:"Configuration settings"},
{q:"What is screen timeout used for on mobile devices today?", options:["Restart device","Turn off display after inactivity","Boost CPU","Encrypt data"], correct:"Turn off display after inactivity"},
{q:"What is USB-C connector known for compared to older connectors?", options:["One-way connection","Reversible design","Slower speeds","Analog only"], correct:"Reversible design"},
{q:"What is Lightning connector primarily associated with in mobile devices today?", options:["Android devices","Apple devices","Fiber connections","Networking"], correct:"Apple devices"},
{q:"What is a common mobile security threat that affects user devices today?", options:["Dust","Malware","Overheating","Low battery"], correct:"Malware"},
{q:"What is application permission control used for on mobile operating systems?", options:["Manage access rights","Delete apps","Update OS","Charge device"], correct:"Manage access rights"},
{q:"What is geolocation used for in mobile applications and services today?", options:["Storage","Device location tracking","Routing data","Encryption"], correct:"Device location tracking"},
{q:"What is screen resolution referring to on mobile device displays today?", options:["Battery size","Pixel count","Storage size","Signal strength"], correct:"Pixel count"},
{q:"What is OS fragmentation referring to in mobile device ecosystems today?", options:["Storage issue","Multiple OS versions in use","Network issue","Battery issue"], correct:"Multiple OS versions in use"},
{q:"What is application caching used for in mobile devices today?", options:["Delete data","Store temporary data","Encrypt files","Update OS"], correct:"Store temporary data"},
{q:"What is a push notification used for in mobile applications today?", options:["Manual message","Automatic alert","File transfer","Network error"], correct:"Automatic alert"},
{q:"What is Do Not Disturb mode used for on mobile devices today?", options:["Boost speed","Silence notifications","Increase signal","Encrypt data"], correct:"Silence notifications"},
{q:"What is a QR code typically used for in mobile device functionality?", options:["Storage","Quick data access","Networking","Encryption"], correct:"Quick data access"},
{q:"What is mobile backup used for in protecting user data today?", options:["Delete data","Save copies of data","Encrypt data","Increase speed"], correct:"Save copies of data"},
{q:"What is screen mirroring used for between mobile devices and displays today?", options:["Copy display output","Rotate screen","Increase brightness","Lock device"], correct:"Copy display output"},
{q:"What is the purpose of mobile system updates released regularly today?", options:["Reduce storage","Improve security and features","Delete apps","Disable hardware"], correct:"Improve security and features"},
{q:"What is a common symptom of a failing mobile battery today?", options:["Faster charging","Rapid battery drain","Increased signal strength","Faster performance"], correct:"Rapid battery drain"},
{q:"What is the purpose of biometric lock fallback methods on devices today?", options:["Backup authentication method","Increase speed","Improve signal","Store data"], correct:"Backup authentication method"},
{q:"Which protocol automatically assigns IP addresses to devices on a local network?", options:["DNS","DHCP","ARP","ICMP"], correct:"DHCP"},
{q:"What is the primary function of the Domain Name System in networking?", options:["Assign IP addresses","Resolve domain names to IP addresses","Encrypt traffic","Route packets"], correct:"Resolve domain names to IP addresses"},
{q:"Which device is primarily responsible for connecting multiple different networks together?", options:["Switch","Router","Hub","Repeater"], correct:"Router"},
{q:"What is the main function of a network switch within a local network?", options:["Route internet traffic","Connect devices within LAN","Assign IP addresses","Filter packets"], correct:"Connect devices within LAN"},
{q:"What does a hub do when receiving data from one connected device?", options:["Sends to one device","Broadcasts to all ports","Filters traffic","Encrypts packets"], correct:"Broadcasts to all ports"},
{q:"What is the primary purpose of a firewall in a network environment?", options:["Store files","Filter network traffic","Increase speed","Assign IP addresses"], correct:"Filter network traffic"},
{q:"What type of IP address is used only within private internal networks?", options:["Public IP","Private IP","Loopback","Broadcast"], correct:"Private IP"},
{q:"Which IP address is reserved specifically for loopback testing purposes?", options:["192.168.1.1","10.0.0.1","127.0.0.1","8.8.8.8"], correct:"127.0.0.1"},
{q:"What does APIPA assign when a DHCP server is unavailable on network?", options:["Public IP","Automatic private IP","Static IP","Loopback address"], correct:"Automatic private IP"},
{q:"What is the primary function of NAT in network communication processes?", options:["Encrypt traffic","Translate IP addresses","Assign IP addresses","Filter traffic"], correct:"Translate IP addresses"},
{q:"What does bandwidth represent in terms of network performance and data transmission?", options:["Delay","Maximum data capacity","Packet loss","Error rate"], correct:"Maximum data capacity"},
{q:"What is latency referring to in network communication and performance measurements?", options:["Speed","Delay","Capacity","Throughput"], correct:"Delay"},
{q:"What does jitter describe in terms of network traffic performance variability?", options:["Packet size","Delay variation","Speed","Signal strength"], correct:"Delay variation"},
{q:"What is packet loss referring to during data transmission across networks?", options:["Lost data packets","Slow CPU","Storage failure","Memory error"], correct:"Lost data packets"},
{q:"What is a VLAN used for in network configuration and segmentation?", options:["Storage","Separate networks logically","Encryption","Routing"], correct:"Separate networks logically"},
{q:"Which type of cable supports the longest distance for high-speed networking connections?", options:["Cat5e","Fiber optic","Coaxial","USB"], correct:"Fiber optic"},
{q:"What is the maximum recommended length for standard Ethernet cables in networking?", options:["10 meters","50 meters","100 meters","500 meters"], correct:"100 meters"},
{q:"What does Power over Ethernet allow devices to receive through cables?", options:["Data only","Power and data","Power only","Signal only"], correct:"Power and data"},
{q:"What is the main function of a repeater in network infrastructure setups?", options:["Store data","Regenerate signal","Route traffic","Encrypt data"], correct:"Regenerate signal"},
{q:"What is the purpose of a bridge in connecting different network segments?", options:["Store data","Connect networks","Assign IP addresses","Encrypt packets"], correct:"Connect networks"},
{q:"What type of wireless security is considered the strongest available currently?", options:["WEP","WPA","WPA2","WPA3"], correct:"WPA3"},
{q:"What does SSID represent in wireless networking configurations and connections?", options:["Password","Network name","IP address","Port number"], correct:"Network name"},
{q:"What is a common disadvantage of using the 2.4 GHz wireless band?", options:["Faster speeds","More interference","Better security","Shorter range"], correct:"More interference"},
{q:"What is an advantage of using the 5 GHz wireless band?", options:["More interference","Less congestion","Slower speeds","Longer range"], correct:"Less congestion"},
{q:"What is the primary purpose of a VPN connection in networking?", options:["Storage","Secure communication tunnel","Routing","Switching"], correct:"Secure communication tunnel"},
{q:"Which command is used to display current IP configuration on a system?", options:["ping","ipconfig","tracert","netstat"], correct:"ipconfig"},
{q:"Which command is commonly used to test connectivity between two network devices?", options:["ping","ipconfig","route","netstat"], correct:"ping"},
{q:"Which command is used to trace the path packets take to destination?", options:["ping","tracert","ipconfig","nslookup"], correct:"tracert"},
{q:"Which port number is used by DNS for domain name resolution services?", options:["25","53","80","443"], correct:"53"},
{q:"Which port number is used by HTTP for standard web traffic communication?", options:["80","21","22","443"], correct:"80"},
{q:"Which port number is used by HTTPS for secure web traffic communication?", options:["80","21","443","25"], correct:"443"},
{q:"Which port number is used by FTP for file transfer control operations?", options:["20","21","22","23"], correct:"21"},
{q:"Which port number is used by SSH for secure remote login access?", options:["21","22","23","25"], correct:"22"},
{q:"Which port number is used by RDP for remote desktop connections?", options:["22","80","3389","5900"], correct:"3389"},
{q:"What is the purpose of a subnet mask in IP addressing schemes?", options:["Assign IP","Divide network and host portions","Encrypt traffic","Route packets"], correct:"Divide network and host portions"},
{q:"What is the purpose of a default gateway in network communication processes?", options:["DNS resolution","Route traffic outside network","Assign IP","Encrypt data"], correct:"Route traffic outside network"},
{q:"What is IPv4 addressing length measured in bits for standard configurations?", options:["32-bit","64-bit","128-bit","16-bit"], correct:"32-bit"},
{q:"What is IPv6 addressing length measured in bits for modern networks?", options:["32-bit","64-bit","128-bit","256-bit"], correct:"128-bit"},
{q:"What is a broadcast transmission in networking communication typically used for?", options:["Send to one","Send to all devices","Send to router","Send to DNS"], correct:"Send to all devices"},
{q:"What is multicast transmission typically used for in network communication scenarios?", options:["One-to-one","One-to-many group","All devices","None"], correct:"One-to-many group"},
{q:"What is unicast communication in networking used to describe data transmission?", options:["One-to-one","One-to-many","All devices","Broadcast"], correct:"One-to-one"},
{q:"What does QoS help manage in network traffic and data prioritization?", options:["Storage","Traffic priority","Encryption","Addressing"], correct:"Traffic priority"},
{q:"What is duplex communication referring to in networking operations?", options:["Cable type","Data direction","Storage","Protocol"], correct:"Data direction"},
{q:"What is full duplex communication allowing devices to do simultaneously?", options:["Send only","Receive only","Send and receive","None"], correct:"Send and receive"},
{q:"What is half duplex communication allowing devices to do at a time?", options:["Send and receive","One direction only","Full speed","No data"], correct:"One direction only"},
{q:"What is a patch panel used for in structured cabling environments?", options:["Storage","Cable organization","Routing","Encryption"], correct:"Cable organization"},
{q:"What is port forwarding used for in network configurations today?", options:["Block traffic","Direct traffic to device","Encrypt data","Assign IP"], correct:"Direct traffic to device"},
{q:"What is a MAC address uniquely identifying on network interfaces today?", options:["Network location","Physical device","Domain name","Port"], correct:"Physical device"},
{q:"What is ARP used for in network communication processes today?", options:["Resolve IP to MAC","Resolve MAC to IP","DNS lookup","Routing"], correct:"Resolve IP to MAC"},
{q:"What is ICMP primarily used for in network diagnostics and troubleshooting?", options:["File transfer","Error reporting","Email","DNS resolution"], correct:"Error reporting"},
{q:"What is the primary function of a CPU in modern computer systems?", options:["Store data permanently","Process instructions and calculations","Display graphics output","Route network traffic"], correct:"Process instructions and calculations"},
{q:"What type of memory temporarily stores data while programs are running?", options:["SSD","RAM","HDD","ROM"], correct:"RAM"},
{q:"Which component is responsible for rendering images and video output?", options:["CPU","GPU","RAM","NIC"], correct:"GPU"},
{q:"What does a power supply unit provide to internal computer components?", options:["Data storage","Electrical power","Cooling","Networking"], correct:"Electrical power"},
{q:"Which storage type uses spinning platters to store data magnetically?", options:["SSD","HDD","NVMe","Flash drive"], correct:"HDD"},
{q:"What is the purpose of a motherboard in a computer system?", options:["Store files","Connect all components together","Process data","Provide internet"], correct:"Connect all components together"},
{q:"What does a heat sink do when attached to a CPU?", options:["Increase speed","Dissipate heat","Store data","Provide power"], correct:"Dissipate heat"},
{q:"What is thermal paste used for between CPU and heat sink?", options:["Increase voltage","Improve heat transfer","Store energy","Clean components"], correct:"Improve heat transfer"},
{q:"Which connector is used for internal SATA data connections?", options:["PCIe","SATA","Molex","USB"], correct:"SATA"},
{q:"What type of slot is used for modern graphics cards today?", options:["PCI","AGP","PCIe x16","ISA"], correct:"PCIe x16"},
{q:"What does BIOS primarily control during system startup process?", options:["Applications","Hardware initialization","Network traffic","Storage only"], correct:"Hardware initialization"},
{q:"What is UEFI used for in modern computer systems today?", options:["Storage","Replace legacy BIOS","Networking","Cooling"], correct:"Replace legacy BIOS"},
{q:"What is RAID 1 primarily used for in storage configurations?", options:["Speed","Mirroring data","Striping","No redundancy"], correct:"Mirroring data"},
{q:"What is RAID 0 primarily used for in storage configurations?", options:["Redundancy","Striping data","Mirroring","Backup"], correct:"Striping data"},
{q:"What does a CMOS battery help maintain when system is powered off?", options:["OS files","BIOS settings","Storage","GPU memory"], correct:"BIOS settings"},
{q:"What does POST check when a computer is powered on initially?", options:["Network","Hardware components","Applications","Storage only"], correct:"Hardware components"},
{q:"What is a form factor referring to in computer hardware design?", options:["Software version","Physical size and layout","Speed rating","Power usage"], correct:"Physical size and layout"},
{q:"What is the difference between ATX and Micro-ATX motherboards?", options:["Speed","Size and expansion slots","Storage type","Power usage"], correct:"Size and expansion slots"},
{q:"What type of connector is RJ-45 commonly used for?", options:["Power","Ethernet networking","Video","Storage"], correct:"Ethernet networking"},
{q:"What does PSU wattage rating indicate for a computer system?", options:["Speed","Power capacity","Storage size","Voltage only"], correct:"Power capacity"},
{q:"What is ECC memory primarily used for in enterprise systems?", options:["Gaming","Error correction","Storage","Graphics"], correct:"Error correction"},
{q:"What is a DIMM used for in desktop computers today?", options:["Storage","RAM module","Power","Networking"], correct:"RAM module"},
{q:"What is a SO-DIMM used for in laptop computers today?", options:["GPU","Laptop RAM","Storage","Networking"], correct:"Laptop RAM"},
{q:"What type of port is HDMI used for on computers today?", options:["Networking","Video and audio","Power","Storage"], correct:"Video and audio"},
{q:"What type of storage device uses flash memory for fast access?", options:["HDD","SSD","Tape","Optical"], correct:"SSD"},
{q:"What is NVMe storage known for compared to SATA SSD drives?", options:["Slower speeds","Faster performance","Larger size","More heat"], correct:"Faster performance"},
{q:"What is the purpose of a fan inside a computer case?", options:["Store data","Cool components","Provide power","Connect devices"], correct:"Cool components"},
{q:"What is a common symptom of failing RAM in a computer system?", options:["Faster performance","Random crashes","Better graphics","Improved speed"], correct:"Random crashes"},
{q:"What happens when a CPU overheats during normal computer operation?", options:["Speed increases","System shuts down","Storage fails","Network drops"], correct:"System shuts down"},
{q:"What is a common cause of overheating in computer systems today?", options:["Extra RAM","Dust buildup","SSD usage","Ethernet cable"], correct:"Dust buildup"},
{q:"What tool is used to measure voltage in computer hardware diagnostics?", options:["Cable tester","Multimeter","Toner probe","Loopback plug"], correct:"Multimeter"},
{q:"What tool is used to test network cable connections for continuity?", options:["Multimeter","Cable tester","Toner","Screwdriver"], correct:"Cable tester"},
{q:"What is the function of a toner probe in network troubleshooting?", options:["Measure voltage","Locate cables","Test RAM","Check GPU"], correct:"Locate cables"},
{q:"What type of storage uses optical discs such as DVDs or Blu-rays?", options:["SSD","HDD","Optical drive","Flash drive"], correct:"Optical drive"},
{q:"What is a common connector used for older hard drives before SATA?", options:["PCIe","IDE","USB-C","HDMI"], correct:"IDE"},
{q:"What is the purpose of a KVM switch in IT environments?", options:["Storage","Control multiple computers","Network routing","Power supply"], correct:"Control multiple computers"},
{q:"What is a common use for USB ports on computers today?", options:["Networking only","Connect peripherals","Power supply","Cooling"], correct:"Connect peripherals"},
{q:"What is the function of a sound card in a computer system?", options:["Graphics","Audio processing","Storage","Networking"], correct:"Audio processing"},
{q:"What is the function of a network interface card in systems?", options:["Storage","Network connectivity","Graphics","Power"], correct:"Network connectivity"},
{q:"What is a common symptom of a failing power supply unit?", options:["Faster performance","Random shutdowns","Better graphics","Increased storage"], correct:"Random shutdowns"},
{q:"What is virtualization primarily used for in modern computing environments today?", options:["Increase storage","Run multiple systems on one machine","Improve cooling","Increase voltage"], correct:"Run multiple systems on one machine"},
{q:"What is a virtual machine in computing environments today?", options:["Physical computer","Software-based computer system","Router","Switch"], correct:"Software-based computer system"},
{q:"What is a hypervisor responsible for in virtualization systems?", options:["Storage","Managing virtual machines","Networking","Cooling"], correct:"Managing virtual machines"},
{q:"What is cloud computing primarily used for in modern IT environments?", options:["Local storage","Internet-based services","Hardware only","Cooling"], correct:"Internet-based services"},
{q:"What does SaaS provide to users in cloud computing environments?", options:["Hardware","Software applications","Networking","Storage only"], correct:"Software applications"},
{q:"What does IaaS provide to users in cloud computing environments?", options:["Applications","Infrastructure resources","Platforms","Software only"], correct:"Infrastructure resources"},
{q:"What does PaaS provide developers in cloud computing environments?", options:["Hardware","Development platform","Storage only","Networking"], correct:"Development platform"},
{q:"What is a public cloud environment used for in organizations today?", options:["Internal only","Shared external services","Offline systems","Personal storage"], correct:"Shared external services"},
{q:"What is a private cloud used for within organizations today?", options:["Public use","Internal use only","Gaming","Storage only"], correct:"Internal use only"},
{q:"What is a hybrid cloud combining in modern cloud environments today?", options:["Public and private cloud","Storage and CPU","RAM and disk","LAN and WAN"], correct:"Public and private cloud"},
{q:"What is the first step in the troubleshooting process according to CompTIA methodology?", options:["Fix the issue immediately","Identify the problem clearly","Replace hardware components","Restart the system"], correct:"Identify the problem clearly"},
{q:"What should be checked first when a desktop computer will not power on?", options:["Installed operating system","Power cable and outlet connection","Network configuration settings","Printer connection"], correct:"Power cable and outlet connection"},
{q:"A system powers on but shows no display; what is most likely issue?", options:["Keyboard failure","GPU or RAM problem","Network failure","Printer error"], correct:"GPU or RAM problem"},
{q:"What tool should be used to safely measure voltage in a power supply?", options:["Cable tester","Multimeter","Toner probe","Loopback plug"], correct:"Multimeter"},
{q:"What is a common symptom of overheating inside a computer system?", options:["Increased performance","Random shutdowns","Faster boot times","Better graphics"], correct:"Random shutdowns"},
{q:"What should be checked first when a laptop battery is not charging properly?", options:["Operating system","Power adapter and cable","Installed applications","Wi-Fi settings"], correct:"Power adapter and cable"},
{q:"What is the most likely cause of intermittent network connectivity issues?", options:["Too much storage","Wireless interference","Updated BIOS","New RAM"], correct:"Wireless interference"},
{q:"What tool is commonly used to test Ethernet cables for proper connectivity?", options:["Multimeter","Cable tester","Toner probe","Screwdriver"], correct:"Cable tester"},
{q:"What should be done before opening a computer case to replace hardware?", options:["Install updates","Disconnect power source","Connect network","Restart system"], correct:"Disconnect power source"},
{q:"What type of issue causes a hard drive to make clicking noises?", options:["Software issue","Mechanical failure","Network error","Power fluctuation"], correct:"Mechanical failure"},
{q:"What is the most likely cause of a “No boot device found” error message?", options:["GPU failure","Missing or failed storage device","Network issue","Printer issue"], correct:"Missing or failed storage device"},
{q:"What tool can help locate cables inside walls during network troubleshooting?", options:["Multimeter","Toner probe","Cable tester","Loopback plug"], correct:"Toner probe"},
{q:"What should be checked first when a printer is not printing any documents?", options:["CPU usage","Printer power and connection","RAM usage","GPU drivers"], correct:"Printer power and connection"},
{q:"What is a common symptom of faulty RAM installed in a computer system?", options:["Faster speeds","Random crashes or errors","Better graphics","Increased storage"], correct:"Random crashes or errors"},
{q:"What does a loopback plug help test in network troubleshooting scenarios?", options:["Storage devices","Network ports functionality","CPU performance","Cooling system"], correct:"Network ports functionality"},
{q:"What is the likely cause of very slow network speeds on wireless devices?", options:["SSD failure","Signal interference","GPU issue","CMOS battery failure"], correct:"Signal interference"},
{q:"What is the purpose of documenting findings after troubleshooting a problem?", options:["Increase speed","Track solutions and prevent repeats","Improve graphics","Delete errors"], correct:"Track solutions and prevent repeats"},
{q:"What should be checked if a monitor displays distorted or flickering images?", options:["Network settings","Display cable and GPU","Printer drivers","Storage device"], correct:"Display cable and GPU"},
{q:"What is the likely cause of a system freezing randomly during operation?", options:["Good RAM","Overheating or memory issue","Strong network","Updated BIOS"], correct:"Overheating or memory issue"},
{q:"What is a common fix for a computer that is overheating frequently?", options:["Add more RAM","Clean dust from fans and vents","Install new OS","Replace keyboard"], correct:"Clean dust from fans and vents"},
{q:"What should be checked if a mobile device will not connect to Wi-Fi network?", options:["Screen brightness","Wireless settings and signal","Battery size","Storage capacity"], correct:"Wireless settings and signal"},
{q:"What is the most likely cause of a computer shutting off under heavy load?", options:["Strong PSU","Overheating CPU","Large storage","Fast SSD"], correct:"Overheating CPU"},
{q:"What is the best tool to check if a network cable is properly wired?", options:["Multimeter","Cable tester","Toner probe","Screwdriver"], correct:"Cable tester"},
{q:"What is the most likely cause of no sound coming from speakers?", options:["GPU failure","Audio settings or drivers","Network issue","Storage failure"], correct:"Audio settings or drivers"},
{q:"What should be checked first when a keyboard is not responding?", options:["CPU temperature","Connection or batteries","Storage device","GPU drivers"], correct:"Connection or batteries"},
{q:"What is a common cause of blue screen errors in operating systems?", options:["Network speed","Driver or hardware failure","Printer issue","Brightness settings"], correct:"Driver or hardware failure"},
{q:"What should be verified when a user cannot access a specific website?", options:["CPU speed","DNS settings","RAM size","GPU type"], correct:"DNS settings"},
{q:"What is the most likely cause of slow boot times on a computer system?", options:["Good SSD","Failing or slow hard drive","Strong GPU","Updated BIOS"], correct:"Failing or slow hard drive"},
{q:"What should be checked first when USB devices are not recognized?", options:["Network connection","USB port or drivers","CPU temperature","Storage size"], correct:"USB port or drivers"},
{q:"What is the most common reason for overheating in laptops?", options:["Too much RAM","Blocked airflow or dust","Strong battery","Updated OS"], correct:"Blocked airflow or dust"},
{q:"What should be done if a system shows incorrect date and time?", options:["Replace GPU","Replace CMOS battery","Update RAM","Restart router"], correct:"Replace CMOS battery"},
{q:"What is a likely cause of intermittent keyboard input issues?", options:["Strong signal","Loose connection or interference","Large storage","Fast CPU"], correct:"Loose connection or interference"},
{q:"What should be checked first when a printer shows paper jam errors?", options:["CPU usage","Paper path and rollers","Network settings","RAM"], correct:"Paper path and rollers"},
{q:"What is the most likely cause of applications crashing frequently?", options:["Good RAM","Software or memory issue","Strong network","High resolution"], correct:"Software or memory issue"},
{q:"What should be verified when a system cannot connect to network printer?", options:["GPU settings","Network connectivity and IP","Storage size","CPU speed"], correct:"Network connectivity and IP"},
{q:"What is a likely cause of poor audio quality on a computer system?", options:["Strong GPU","Driver or hardware issue","Storage failure","Brightness settings"], correct:"Driver or hardware issue"},
{q:"What should be done if a computer is infected with malware?", options:["Ignore issue","Run antivirus software","Increase RAM","Replace GPU"], correct:"Run antivirus software"},
{q:"What is a common cause of slow application performance on computers?", options:["Strong CPU","Insufficient RAM","Fast SSD","Good cooling"], correct:"Insufficient RAM"},
{q:"What should be checked when a display shows no signal error message?", options:["Storage device","Cable or GPU connection","Network settings","Printer"], correct:"Cable or GPU connection"},
{q:"What is the most likely cause of overheating in desktop computers?", options:["Extra RAM","Dust and poor airflow","SSD usage","Ethernet cable"], correct:"Dust and poor airflow"},
{q:"What should be verified if a user cannot send emails from client?", options:["GPU driver","SMTP settings","RAM usage","Storage space"], correct:"SMTP settings"},
{q:"What is a likely cause of slow internet browsing speeds?", options:["Strong signal","Network congestion","Fast CPU","Large SSD"], correct:"Network congestion"},
{q:"What should be checked when a system fan is making loud noise?", options:["Storage device","Dust buildup or failing fan","Network cable","RAM size"], correct:"Dust buildup or failing fan"},
{q:"What is the most likely cause of random system restarts?", options:["Stable PSU","Power or overheating issue","Strong network","Updated OS"], correct:"Power or overheating issue"},
{q:"What should be done if a device driver is causing system instability?", options:["Ignore issue","Update or reinstall driver","Replace CPU","Upgrade storage"], correct:"Update or reinstall driver"},
{q:"What is a likely cause of a system not recognizing new hardware?", options:["Strong PSU","Missing drivers","Fast CPU","Large storage"], correct:"Missing drivers"},
{q:"What should be verified if a user cannot access shared network resources?", options:["GPU settings","Permissions and network connectivity","Storage device","CPU speed"], correct:"Permissions and network connectivity"},
{q:"What is the most likely cause of corrupted files on storage devices?", options:["Strong CPU","Disk errors or failure","Fast RAM","Network speed"], correct:"Disk errors or failure"},
{q:"What should be checked when a system runs very slowly unexpectedly?", options:["GPU only","Background processes and resources","Printer settings","Screen resolution"], correct:"Background processes and resources"},
{q:"What is the final step after successfully resolving a technical issue?", options:["Restart system","Document solution and results","Replace hardware","Ignore problem"], correct:"Document solution and results"},
{q:"A user reports slow performance after adding RAM. What is most likely issue?", options:["Faulty GPU","Mismatched RAM speeds","Bad monitor","Network issue"], correct:"Mismatched RAM speeds"},
{q:"A PC powers on but does not POST. What should be checked first?", options:["Hard drive","RAM seating","Network cable","Printer"], correct:"RAM seating"},
{q:"A laptop overheats during use. What is the best initial troubleshooting step?", options:["Replace CPU","Clean vents and fans","Install new OS","Replace battery"], correct:"Clean vents and fans"},
{q:"A user cannot access websites but can ping IP addresses. What is issue?", options:["DHCP problem","DNS problem","GPU failure","RAM issue"], correct:"DNS problem"},
{q:"A technician installs a new GPU but gets no display output. What likely issue?", options:["Missing power connection","Bad keyboard","Network problem","Printer issue"], correct:"Missing power connection"},
{q:"A user reports intermittent Wi-Fi drops in office environment. What is likely cause?", options:["SSD failure","Wireless interference","CPU overheating","Power supply issue"], correct:"Wireless interference"},
{q:"A system clock resets after shutdown. What component should be replaced?", options:["RAM","CMOS battery","GPU","SSD"], correct:"CMOS battery"},
{q:"A user hears clicking noise from hard drive. What is best action?", options:["Ignore noise","Backup and replace drive","Install drivers","Restart system"], correct:"Backup and replace drive"},
{q:"A network cable tests bad on one pair. What is likely issue?", options:["IP conflict","Broken wire","DNS issue","GPU problem"], correct:"Broken wire"},
{q:"A PC randomly shuts down under heavy load. What is most likely cause?", options:["Strong PSU","Overheating CPU","Fast SSD","Updated BIOS"], correct:"Overheating CPU"},
{q:"A user cannot connect to secure website using HTTPS. What port should be checked?", options:["80","443","21","25"], correct:"443"},
{q:"A printer is online but not printing jobs. What should be checked first?", options:["GPU","Print queue","RAM","CPU"], correct:"Print queue"},
{q:"A technician needs fastest storage for OS installation. What should be used?", options:["HDD","NVMe SSD","Optical drive","Tape"], correct:"NVMe SSD"},
{q:"A user connects to Wi-Fi but has no internet access. What should be checked?", options:["GPU","Default gateway","RAM","Monitor"], correct:"Default gateway"},
{q:"A system shows artifacting on screen during gaming. What is likely failing?", options:["RAM","GPU","SSD","NIC"], correct:"GPU"},
{q:"A laptop battery drains quickly even when idle. What is best solution?", options:["Replace battery","Upgrade RAM","Replace SSD","Update GPU"], correct:"Replace battery"},
{q:"A user wants redundancy and performance in storage. Which RAID should be used?", options:["RAID 0","RAID 1","RAID 5","RAID 10"], correct:"RAID 10"},
{q:"A system cannot obtain IP address automatically. What service may be down?", options:["DNS","DHCP","ARP","NAT"], correct:"DHCP"},
{q:"A technician wants to separate network traffic logically. What should be configured?", options:["VPN","VLAN","NAT","DNS"], correct:"VLAN"},
{q:"A device shows IP address 169.254.x.x. What does this indicate?", options:["Public IP","APIPA address","Static IP","Loopback"], correct:"APIPA address"},
{q:"A user reports slow file transfers over network. What should be checked first?", options:["CPU","Bandwidth and congestion","GPU","Printer"], correct:"Bandwidth and congestion"},
{q:"A system shows “No boot device found” during startup. What is likely issue?", options:["GPU","Storage failure","RAM","NIC"], correct:"Storage failure"},
{q:"A technician installs RAM but system becomes unstable. What is likely cause?", options:["Wrong keyboard","Incompatible RAM","Bad monitor","Network error"], correct:"Incompatible RAM"},
{q:"A user cannot print from one computer but others can. What is issue?", options:["Printer broken","Local configuration issue","Network down","Power failure"], correct:"Local configuration issue"},
{q:"A technician needs to test network port functionality. What tool should be used?", options:["Multimeter","Loopback plug","Toner probe","Screwdriver"], correct:"Loopback plug"},
{q:"A mobile device cannot connect to cellular network. What should be checked?", options:["GPU","SIM card","RAM","SSD"], correct:"SIM card"},
{q:"A user wants to securely connect to corporate network remotely. What should be used?", options:["FTP","VPN","HTTP","SMB"], correct:"VPN"},
{q:"A system is slow when many applications are open. What upgrade helps most?", options:["GPU","RAM","Monitor","Keyboard"], correct:"RAM"},
{q:"A technician wants to increase Wi-Fi coverage in building. What should be added?", options:["Switch","Access point","GPU","Printer"], correct:"Access point"},
{q:"A user cannot access shared files on network. What should be checked?", options:["Permissions","GPU","SSD","CPU"], correct:"Permissions"},
{q:"A laptop screen is dim even at max brightness. What is likely issue?", options:["GPU","Backlight failure","RAM","Storage"], correct:"Backlight failure"},
{q:"A system fan is loud and vibrating. What is most likely cause?", options:["Network issue","Failing fan","RAM issue","GPU issue"], correct:"Failing fan"},
{q:"A technician wants to verify DNS resolution. What command should be used?", options:["ping","nslookup","ipconfig","netstat"], correct:"nslookup"},
{q:"A user reports slow boot times. What upgrade provides biggest improvement?", options:["More RAM","SSD instead of HDD","New monitor","Better keyboard"], correct:"SSD instead of HDD"},
{q:"A printer produces faded output. What is likely cause?", options:["Network issue","Low toner or ink","RAM issue","CPU issue"], correct:"Low toner or ink"},
{q:"A technician needs to connect multiple computers to one monitor. What device used?", options:["Switch","KVM switch","Router","Hub"], correct:"KVM switch"},
{q:"A system loses date and time after reboot. What should be replaced?", options:["RAM","CMOS battery","GPU","SSD"], correct:"CMOS battery"},
{q:"A user reports slow Wi-Fi speeds during peak hours. What is cause?", options:["SSD","Network congestion","GPU","RAM"], correct:"Network congestion"},
{q:"A technician installs new CPU but system will not boot. What should be checked?", options:["GPU","BIOS compatibility","Printer","Network"], correct:"BIOS compatibility"},
{q:"A user cannot hear audio from speakers. What should be checked first?", options:["GPU","Audio settings","RAM","SSD"], correct:"Audio settings"},
{q:"A system shows blue screen errors after driver update. What is best action?", options:["Ignore","Roll back driver","Replace CPU","Add RAM"], correct:"Roll back driver"},
{q:"A user wants to secure Wi-Fi network. What should be enabled?", options:["WEP","WPA3","Open network","None"], correct:"WPA3"},
{q:"A device cannot connect to Bluetooth accessory. What should be checked?", options:["GPU","Pairing status","RAM","SSD"], correct:"Pairing status"},
{q:"A technician wants to test internet latency. What command should be used?", options:["ipconfig","ping","netstat","route"], correct:"ping"},
{q:"A system randomly freezes during gaming sessions. What is likely issue?", options:["GPU overheating","Printer issue","Network issue","Storage issue"], correct:"GPU overheating"},
{q:"A technician wants to isolate network traffic between departments. What should be used?", options:["VPN","VLAN","DNS","NAT"], correct:"VLAN"},
{q:"A user’s screen flickers intermittently. What should be checked first?", options:["Network","Display cable","Storage","CPU"], correct:"Display cable"},
{q:"A laptop does not charge when plugged in. What should be checked first?", options:["RAM","Power adapter","GPU","SSD"], correct:"Power adapter"},
{q:"A user cannot access internal server but internet works. What is likely issue?", options:["GPU","DNS or routing issue","RAM","Storage"], correct:"DNS or routing issue"},
{q:"A technician wants to ensure system stability after repair. What should be done?", options:["Ignore","Stress test system","Replace CPU","Upgrade RAM"], correct:"Stress test system"},
{q:"A technician installs DDR4 RAM into a DDR3 motherboard. What will happen?", options:["Reduced performance","System will not boot","RAM runs at lower speed","No issue"], correct:"System will not boot"},
{q:"A user reports intermittent connectivity only on wireless devices. What is likely cause?", options:["Bad switch","Wireless interference","Faulty SSD","Incorrect BIOS"], correct:"Wireless interference"},
{q:"A system has correct IP but cannot reach gateway. What is likely issue?", options:["DNS failure","Routing or gateway misconfiguration","GPU failure","RAM issue"], correct:"Routing or gateway misconfiguration"},
{q:"A technician installs RAID 0 on two drives. What is the main risk?", options:["Reduced speed","No redundancy","Higher latency","Less storage"], correct:"No redundancy"},
{q:"A user reports slow network performance only during peak hours. What is cause?", options:["Hardware failure","Network congestion","DNS failure","GPU issue"], correct:"Network congestion"},
{q:"A laptop connects to Wi-Fi but gets APIPA address. What is issue?", options:["DNS failure","DHCP failure","GPU problem","Storage issue"], correct:"DHCP failure"},
{q:"A technician replaces PSU but system still shuts down under load. What next?", options:["Replace SSD","Check CPU cooling","Replace RAM","Update BIOS"], correct:"Check CPU cooling"},
{q:"A system boots but crashes during OS load. What is most likely issue?", options:["GPU failure","Corrupt OS or RAM issue","Network issue","Printer issue"], correct:"Corrupt OS or RAM issue"},
{q:"A user cannot access internal server but external websites load fine. Why?", options:["GPU issue","DNS or routing issue","RAM issue","Storage failure"], correct:"DNS or routing issue"},
{q:"A technician installs new CPU but system will not POST. Why?", options:["Wrong keyboard","BIOS incompatibility","Bad monitor","Network failure"], correct:"BIOS incompatibility"},
{q:"A user experiences screen tearing during gaming sessions. What should be adjusted?", options:["RAM speed","Refresh rate or V-Sync","Storage type","CPU voltage"], correct:"Refresh rate or V-Sync"},
{q:"A network printer is reachable by IP but not by hostname. What is issue?", options:["DHCP failure","DNS resolution issue","GPU problem","RAM failure"], correct:"DNS resolution issue"},
{q:"A system shows high temperatures despite clean fans. What is likely issue?", options:["Faulty SSD","Improper thermal paste","Network congestion","Bad keyboard"], correct:"Improper thermal paste"},
{q:"A user wants fastest possible storage interface for workstation. What should be used?", options:["SATA HDD","NVMe PCIe SSD","Optical drive","USB drive"], correct:"NVMe PCIe SSD"},
{q:"A technician needs to prioritize VoIP traffic on network. What should be used?", options:["NAT","QoS","DNS","VLAN only"], correct:"QoS"},
{q:"A user cannot connect to secure website but HTTP works. What is issue?", options:["Port 80 blocked","Port 443 blocked","DNS failure","GPU issue"], correct:"Port 443 blocked"},
{q:"A system intermittently loses time and BIOS settings. What is root cause?", options:["RAM failure","CMOS battery failure","GPU issue","SSD failure"], correct:"CMOS battery failure"},
{q:"A technician notices duplicate IP addresses on network. What is happening?", options:["DNS issue","IP conflict","GPU problem","RAM mismatch"], correct:"IP conflict"},
{q:"A laptop battery shows 100% but dies immediately unplugged. What is issue?", options:["GPU","Battery failure","RAM","SSD"], correct:"Battery failure"},
{q:"A user reports weak Wi-Fi signal in one office area. Best solution?", options:["Replace CPU","Add access point","Upgrade RAM","Replace SSD"], correct:"Add access point"},
{q:"A technician runs ping but sees high latency spikes. What does this indicate?", options:["Storage failure","Network instability","GPU issue","RAM failure"], correct:"Network instability"},
{q:"A system shows artifacting only under heavy load. What component failing?", options:["SSD","GPU","NIC","RAM"], correct:"GPU"},
{q:"A technician configures VLAN but devices still communicate freely. Why?", options:["VLAN unsupported switch","Incorrect DNS","GPU failure","RAM issue"], correct:"VLAN unsupported switch"},
{q:"A user connects to Wi-Fi but receives no internet. What should be checked?", options:["GPU","Default gateway","RAM","SSD"], correct:"Default gateway"},
{q:"A technician wants to test network path between systems. What tool used?", options:["ipconfig","tracert","netstat","route"], correct:"tracert"},
{q:"A system experiences slow performance when many applications run. Root cause?", options:["GPU","Insufficient RAM","SSD failure","NIC issue"], correct:"Insufficient RAM"},
{q:"A printer prints blank pages intermittently. What is likely cause?", options:["Network issue","Low or faulty toner","RAM issue","CPU failure"], correct:"Low or faulty toner"},
{q:"A technician hears grinding noise from system. What is failing?", options:["SSD","HDD","RAM","GPU"], correct:"HDD"},
{q:"A user cannot access shared drive but network is fine. What issue?", options:["GPU","Permissions issue","RAM","SSD"], correct:"Permissions issue"},
{q:"A technician installs wrong PSU wattage. What symptom appears?", options:["Faster speed","System instability or shutdowns","Better graphics","Increased storage"], correct:"System instability or shutdowns"},
{q:"A system shows no display after RAM upgrade. What should be checked?", options:["GPU","RAM compatibility/seating","SSD","NIC"], correct:"RAM compatibility/seating"},
{q:"A user reports slow file transfers over LAN. What should be checked?", options:["CPU","Network bandwidth","GPU","RAM"], correct:"Network bandwidth"},
{q:"A technician needs to isolate broadcast traffic. What should be used?", options:["DNS","VLAN","NAT","FTP"], correct:"VLAN"},
{q:"A user cannot send emails but can receive them. What is likely issue?", options:["POP3","SMTP","DNS","ARP"], correct:"SMTP"},
{q:"A system displays “Operating System not found.” What is issue?", options:["GPU","Boot device missing or failed","RAM","NIC"], correct:"Boot device missing or failed"},
{q:"A technician wants redundancy without sacrificing performance. Best RAID?", options:["RAID 0","RAID 1","RAID 5","RAID 10"], correct:"RAID 10"},
{q:"A device cannot resolve hostnames but IP works. What is issue?", options:["GPU","DNS","RAM","SSD"], correct:"DNS"},
{q:"A user experiences dropped VoIP calls randomly. What is likely issue?", options:["GPU","Network jitter","RAM","SSD"], correct:"Network jitter"},
{q:"A technician installs incorrect CPU socket type. What happens?", options:["Slower speed","System will not boot","Reduced storage","Network failure"], correct:"System will not boot"},
{q:"A user’s Wi-Fi works but Ethernet does not. What should be checked?", options:["GPU","NIC or cable","RAM","SSD"], correct:"NIC or cable"},
{q:"A system shows frequent BSOD errors after driver update. What is fix?", options:["Replace CPU","Roll back driver","Add RAM","Upgrade GPU"], correct:"Roll back driver"},
{q:"A technician needs to test port connectivity quickly. What tool used?", options:["Multimeter","Loopback plug","Toner probe","Screwdriver"], correct:"Loopback plug"},
{q:"A user reports very slow boot times on HDD system. Best upgrade?", options:["GPU","SSD","RAM","NIC"], correct:"SSD"},
{q:"A laptop shuts down when unplugged despite showing charge. What issue?", options:["GPU","Battery failure","RAM","SSD"], correct:"Battery failure"},
{q:"A system has proper IP but cannot reach internet. What likely missing?", options:["GPU","Default gateway","RAM","SSD"], correct:"Default gateway"},
{q:"A technician detects high packet loss during testing. What does this indicate?", options:["GPU failure","Network issue","RAM failure","Storage issue"], correct:"Network issue"},
{q:"A printer works locally but not over network. What is issue?", options:["GPU","Network configuration","RAM","CPU"], correct:"Network configuration"},
{q:"A technician wants secure remote login access. Which protocol used?", options:["Telnet","SSH","FTP","HTTP"], correct:"SSH"},
{q:"A system fails POST after hardware upgrade. What should be checked first?", options:["Network","Hardware compatibility","Storage","GPU drivers"], correct:"Hardware compatibility"},
{q:"A user wants to protect sensitive data at rest. What should be used?", options:["VPN","Encryption","NAT","DHCP"], correct:"Encryption"},
{q:"A laser printer is producing faded prints. What is the most likely cause?", options:["Low toner cartridge","Bad network cable","Faulty RAM","Incorrect IP address"], correct:"Low toner cartridge"},
{q:"An inkjet printer prints streaks across pages. What should be performed first?", options:["Replace drum","Clean print heads","Replace fuser","Update firmware"], correct:"Clean print heads"},
{q:"A thermal printer produces blank receipts. What is most likely issue?", options:["Incorrect paper type installed","Low toner","Fuser failure","Network issue"], correct:"Incorrect paper type installed"},
{q:"A user reports paper jams frequently in printer tray. What should be checked?", options:["GPU drivers","Rollers and paper alignment","DNS settings","RAM usage"], correct:"Rollers and paper alignment"},
{q:"Which printer type uses toner and heat to fuse images onto paper?", options:["Inkjet printer","Laser printer","Thermal printer","Impact printer"], correct:"Laser printer"},
{q:"Which printer component melts toner onto paper during printing process?", options:["Drum","Fuser assembly","Roller","Transfer belt"], correct:"Fuser assembly"},
{q:"A printer is printing blank pages intermittently. What is likely cause?", options:["Empty toner or ink","Network congestion","GPU failure","Incorrect DNS"], correct:"Empty toner or ink"},
{q:"A technician replaces toner but prints still faded. What should be checked next?", options:["Fuser assembly","NIC","RAM","Keyboard"], correct:"Fuser assembly"},
{q:"What type of printer uses liquid ink sprayed onto paper surface?", options:["Laser printer","Inkjet printer","Thermal printer","Impact printer"], correct:"Inkjet printer"},
{q:"Which printer type is most commonly used for printing receipts in stores?", options:["Inkjet","Laser","Thermal","Dot matrix"], correct:"Thermal"},
{q:"A network printer is reachable by IP but not printing jobs. What should be checked?", options:["Print queue","GPU drivers","RAM","Storage"], correct:"Print queue"},
{q:"What is the purpose of a printer spooler service in operating systems?", options:["Store printed pages","Manage print jobs queue","Control power","Encrypt data"], correct:"Manage print jobs queue"},
{q:"A printer prints garbled text when sending jobs. What is likely cause?", options:["Wrong printer driver installed","Low toner","Paper jam","Bad cable"], correct:"Wrong printer driver installed"},
{q:"Which printer type uses pins striking ribbon against paper?", options:["Laser","Inkjet","Thermal","Impact"], correct:"Impact"},
{q:"A user reports ghost images appearing on printed pages. What is likely issue?", options:["Fuser or drum problem","Network issue","RAM problem","DNS failure"], correct:"Fuser or drum problem"},
{q:"What is the function of a drum inside a laser printer assembly?", options:["Melt toner","Transfer image to paper","Feed paper","Store ink"], correct:"Transfer image to paper"},
{q:"A printer continuously reports “out of paper” when paper is loaded. What is issue?", options:["Faulty paper sensor","GPU failure","RAM issue","DNS problem"], correct:"Faulty paper sensor"},
{q:"A printer is slow only when printing large files. What should be upgraded?", options:["Printer memory","GPU","Monitor","Keyboard"], correct:"Printer memory"},
{q:"A technician wants to share a printer across network. What is required?", options:["Static IP or shared configuration","GPU upgrade","SSD","RAM"], correct:"Static IP or shared configuration"},
{q:"What type of printer produces highest quality photo prints typically?", options:["Laser printer","Inkjet printer","Thermal printer","Impact printer"], correct:"Inkjet printer"},
{q:"A printer prints smudged output. What is most likely failing component?", options:["Fuser assembly","NIC","RAM","SSD"], correct:"Fuser assembly"},
{q:"What is duplex printing capability used for in printers today?", options:["Print two copies","Print both sides of page","Print faster","Print color"], correct:"Print both sides of page"},
{q:"A user cannot print from one workstation but others work fine. Why?", options:["Local configuration issue","Printer failure","Network outage","Power failure"], correct:"Local configuration issue"},
{q:"What is a common connection type for local printers to computers today?", options:["HDMI","USB","VGA","SATA"], correct:"USB"},
{q:"A technician installs printer but system cannot detect it. What should be checked?", options:["Cable connection and drivers","GPU","RAM","Storage"], correct:"Cable connection and drivers"},
{q:"A laser printer prints repeating marks down the page. What is cause?", options:["Damaged drum","DNS issue","RAM problem","Network issue"], correct:"Damaged drum"},
{q:"What type of maintenance is required for inkjet printers regularly?", options:["Replace fuser","Clean print heads","Replace drum","Update BIOS"], correct:"Clean print heads"},
{q:"A thermal printer fades prints over time. What is reason?", options:["Heat-sensitive paper degradation","GPU failure","RAM issue","Network congestion"], correct:"Heat-sensitive paper degradation"},
{q:"A printer connected via USB is not recognized. What should be checked?", options:["Drivers and USB port","GPU","RAM","DNS"], correct:"Drivers and USB port"},
{q:"What type of printer is best for multi-part forms printing?", options:["Laser","Inkjet","Impact printer","Thermal"], correct:"Impact printer"},
{q:"A printer is assigned wrong IP address. What issue will occur?", options:["Cannot connect over network","Prints faster","Better quality","Less noise"], correct:"Cannot connect over network"},
{q:"A technician needs to secure printer access on network. What should be configured?", options:["Permissions and authentication","GPU","RAM","SSD"], correct:"Permissions and authentication"},
{q:"What is the purpose of a transfer roller in laser printers?", options:["Melt toner","Transfer toner to paper","Feed paper","Store toner"], correct:"Transfer toner to paper"},
{q:"A printer prints only blank pages after toner replacement. What is likely issue?", options:["Protective strip not removed","Network issue","RAM issue","GPU issue"], correct:"Protective strip not removed"},
{q:"A user reports printer printing very slowly over network. What is cause?", options:["Network congestion or bandwidth","GPU","RAM","Storage"], correct:"Network congestion or bandwidth"},
{q:"A printer displays error “offline” but is powered on. What is likely issue?", options:["Network connectivity problem","GPU failure","RAM issue","Storage issue"], correct:"Network connectivity problem"},
{q:"What is a print queue used for in printing processes today?", options:["Store hardware","Manage pending print jobs","Store drivers","Power device"], correct:"Manage pending print jobs"},
{q:"A technician wants to assign static IP to printer. Why?", options:["Consistent network access","Faster printing","Better graphics","More storage"], correct:"Consistent network access"},
{q:"What is the function of rollers inside a printer device?", options:["Transfer toner","Move paper through printer","Store ink","Melt toner"], correct:"Move paper through printer"},
{q:"A printer produces wrinkled pages. What is most likely cause?", options:["Fuser overheating or rollers issue","GPU","RAM","Network"], correct:"Fuser overheating or rollers issue"},
{q:"A technician installs wrong printer driver. What symptom occurs?", options:["Garbled or incorrect output","Faster printing","Better quality","Less noise"], correct:"Garbled or incorrect output"},
{q:"A printer connected to network cannot be pinged. What is issue?", options:["Incorrect IP or network problem","GPU","RAM","SSD"], correct:"Incorrect IP or network problem"},
{q:"What is a maintenance kit in laser printers typically used for?", options:["Replace worn components","Upgrade RAM","Improve speed","Add storage"], correct:"Replace worn components"},
{q:"A printer repeatedly jams at same location. What should be checked?", options:["Rollers or obstruction","GPU","RAM","NIC"], correct:"Rollers or obstruction"},
{q:"What type of printer is best suited for high-volume office printing?", options:["Inkjet","Laser printer","Thermal","Impact"], correct:"Laser printer"},
{q:"A printer prints skewed pages. What is likely cause?", options:["Misaligned paper tray","GPU","RAM","Network"], correct:"Misaligned paper tray"},
{q:"A user cannot print due to “access denied.” What is issue?", options:["Permissions problem","GPU","RAM","SSD"], correct:"Permissions problem"},
{q:"What is the function of firmware in printer devices?", options:["Control printer operations","Store files","Provide power","Connect network"], correct:"Control printer operations"},
{q:"A printer is working locally but not over network. What is likely issue?", options:["Network configuration","GPU","RAM","Storage"], correct:"Network configuration"},
{q:"A technician wants to reset printer to defaults. What should be used?", options:["Factory reset option","GPU","RAM","SSD"], correct:"Factory reset option"}
];
