const A1QuizData = [

  {q:"Which type of RAM is most commonly used in modern desktop computers? (2016+)", options:["DDR4","SRAM","RDRAM","VRAM"], correct:"DDR4"},
  {q:"What does DDR stand for?", options:["Double Data Rate","Dual Data RAM","Dynamic Data Read","Direct Data Register"], correct:"Double Data Rate"},
  {q:"Which component converts AC power to DC power in a computer?", options:["Power Supply Unit","Motherboard","CPU","Transformer"], correct:"Power Supply Unit"},
  {q:"What is the purpose of a CPU heat sink?", options:["Increase processing speed","Dissipate heat","Store data","Regulate voltage"], correct:"Dissipate heat"},
  {q:"Which connector is used for internal SATA drives?", options:["SATA","Molex","PCIe","IDE"], correct:"SATA"},
  {q:"Which expansion slot is commonly used for modern graphics cards?", options:["PCIe x16","PCI","AGP","ISA"], correct:"PCIe x16"},
  {q:"What is the main difference between HDD and SSD?", options:["SSD uses flash memory","HDD is faster","SSD has moving parts","HDD is smaller"], correct:"SSD uses flash memory"},
  {q:"What does BIOS stand for?", options:["Basic Input Output System","Binary Integrated Operating System","Basic Internal Operating Setup","Boot Initialization Operating System"], correct:"Basic Input Output System"},
  {q:"What is UEFI?", options:["A modern replacement for BIOS","A type of RAM","A storage device","A network protocol"], correct:"A modern replacement for BIOS"},
  {q:"Which cable type is used for digital video output?", options:["HDMI","VGA","PS/2","Serial"], correct:"HDMI"},
  {q:"What type of storage uses flash memory?", options:["SSD","HDD","Tape","Optical"], correct:"SSD"},
  {q:"What is configuration RAID 1?", options:["Mirroring","Striping","Parity","Backup only"], correct:"Mirroring"},
  {q:"What configuration is RAID 0?", options:["Mirroring","Striping","Parity","Redundancy"], correct:"Striping"},
  {q:"What is the purpose of thermal paste?", options:["Improve heat transfer","Store energy","Increase voltage","Clean components"], correct:"Improve heat transfer"},
  {q:"What connector powers the CPU?", options:["4/8-pin EPS","SATA","Molex","PCI"], correct:"4/8-pin EPS"},
  {q:"What is the function of a CMOS battery?", options:["Maintain BIOS settings","Power the CPU","Cool the system","Store files"], correct:"Maintain BIOS settings"},
  {q:"What does POST stand for?", options:["Power-On Self Test","Primary Operating System Test","Power Output System Test","Peripheral Operating Setup Tool"], correct:"Power-On Self Test"},
  {q:"What is a form factor?", options:["Physical size/layout of hardware","Type of RAM","Software version","Network protocol"], correct:"Physical size/layout of hardware"},
  {q:"What is the difference between ATX and Micro-ATX?", options:["Size and expansion slots","Speed","Power usage","Storage type"], correct:"Size and expansion slots"},
  {q:"What type of connector is RJ-45?", options:["Ethernet","Phone","Video","Power"], correct:"Ethernet"},
  {q:"What does PSU wattage indicate?", options:["Total power output capacity","Speed","Storage","Voltage only"], correct:"Total power output capacity"},
  {q:"What is ECC memory used for?", options:["Error correction","Gaming performance","Graphics rendering","Storage"], correct:"Error correction"},
  {q:"What is a DIMM?", options:["Desktop RAM module","CPU type","Storage device","Power cable"], correct:"Desktop RAM module"},
  {q:"What is a SO-DIMM?", options:["Laptop RAM module","GPU","Hard drive","Network card"], correct:"Laptop RAM module"},
  {q:"What is DisplayPort used for?", options:["Video/audio output","Networking","Power delivery","Storage"], correct:"Video/audio output"},
  {q:"A technician installs new RAM and the system fails to boot with continuous beeping. What is the MOST likely cause?", options:["Faulty PSU","Improperly seated RAM","Corrupt OS","Overheating CPU"], correct:"Improperly seated RAM"},
  {q:"A system intermittently shuts down under heavy load. What should be checked FIRST?", options:["Hard drive health","CPU temperature","Network settings","BIOS version"], correct:"CPU temperature"},
  {q:"Which RAID level provides redundancy with striping and parity?", options:["RAID 0","RAID 1","RAID 5","RAID 10"], correct:"RAID 5"},
  {q:"A user reports slow performance after installing additional RAM. What is the MOST likely issue?", options:["Mismatched RAM speeds","Too much RAM","SSD failure","GPU bottleneck"], correct:"Mismatched RAM speeds"},
  {q:"What component is MOST likely to fail due to power surges?", options:["CPU","PSU","RAM","Case fan"], correct:"PSU"},
  {q:"A technician replaces a motherboard and the system will not power on. What should be checked FIRST?", options:["OS installation","Front panel connectors","GPU drivers","Monitor cable"], correct:"Front panel connectors"},
  {q:"Which connector provides power specifically to PCIe graphics cards?", options:["Molex","SATA","6/8-pin PCIe","24-pin ATX"], correct:"6/8-pin PCIe"},
  {q:"A system displays no video but fans spin. What is the MOST likely issue?", options:["Faulty GPU or RAM","Bad keyboard","Network failure","OS corruption"], correct:"Faulty GPU or RAM"},
  {q:"What is the PRIMARY purpose of ECC memory in servers?", options:["Increase speed","Reduce latency","Detect and correct errors","Improve graphics"], correct:"Detect and correct errors"},
  {q:"A laptop battery drains quickly after a full charge. What is the BEST solution?", options:["Replace battery","Update BIOS","Add RAM","Reinstall OS"], correct:"Replace battery"},
  {q:"A user can access websites via IP but not by domain name. What is the issue?", options:["DHCP failure","DNS issue","NAT problem","Firewall block"], correct:"DNS issue"},
  {q:"Which device operates at Layer 2 of the OSI model?", options:["Router","Switch","Firewall","Modem"], correct:"Switch"},
  {q:"A technician needs to isolate broadcast traffic. What should be implemented?", options:["VLAN","Hub","Repeater","Bridge loop"], correct:"VLAN"},
  {q:"What type of IP address is 169.254.x.x?", options:["Public","Loopback","APIPA","Multicast"], correct:"APIPA"},
  {q:"A user reports intermittent wireless connectivity. What is the MOST likely cause?", options:["IP conflict","Interference","DNS failure","NAT issue"], correct:"Interference"},
  {q:"Which protocol resolves IP addresses to MAC addresses?", options:["DNS","ARP","DHCP","ICMP"], correct:"ARP"},
  {q:"What command verifies connectivity to a remote host?", options:["ipconfig","ping","tracert","netstat"], correct:"ping"},
  {q:"A network cable is limited to 100 meters. What type is it?", options:["Fiber","Coax","Cat5e","Serial"], correct:"Cat5e"},
  {q:"Which wireless standard operates ONLY on 5 GHz?", options:["802.11b","802.11g","802.11n","802.11ac"], correct:"802.11ac"},
  {q:"What is the function of NAT?", options:["Encrypt traffic","Translate private to public IP","Assign IP addresses","Filter packets"], correct:"Translate private to public IP"},
  {q:"A phone cannot connect to cellular network but Wi-Fi works. What is MOST likely?", options:["Bad SIM","Dead battery","OS corruption","Bluetooth issue"], correct:"Bad SIM"},
  {q:"What security method uses fingerprint or face recognition?", options:["Encryption","Biometrics","MFA","Tokenization"], correct:"Biometrics"},
  {q:"A user wants to share internet via phone. What feature is used?", options:["NFC","Tethering","VPN","AirDrop"], correct:"Tethering"},
  {q:"What type of cloud is owned and operated by a third party?", options:["Private","Public","Hybrid","Community"], correct:"Public"},
  {q:"What does SaaS provide?", options:["Hardware","OS control","Software access","Networking only"], correct:"Software access"},

  {q:"Which port does HTTP use?", options:["21","22","80","443"], correct:"80"},
  {q:"Which port is used for HTTPS?", options:["80","110","443","25"], correct:"443"},
  {q:"Which port does FTP use (control)?", options:["20","21","22","23"], correct:"21"},
  {q:"Which port is SSH?", options:["21","22","23","25"], correct:"22"},
  {q:"Which port is Telnet?", options:["22","23","25","53"], correct:"23"},
  {q:"Which port is SMTP?", options:["25","53","110","443"], correct:"25"},
  {q:"Which port is DNS?", options:["25","53","80","443"], correct:"53"},
  {q:"Which port is POP3?", options:["110","143","389","445"], correct:"110"},
  {q:"Which port is IMAP?", options:["110","143","993","995"], correct:"143"},
  {q:"Which port is LDAP?", options:["389","443","3389","8080"], correct:"389"},
  {q:"Which port is RDP?", options:["22","80","3389","5900"], correct:"3389"},
  {q:"Which port is SMB?", options:["135","139","445","389"], correct:"445"},
  {q:"Which port is SNMP?", options:["143","161","389","443"], correct:"161"},
  {q:"Which port is FTPS?", options:["21","990","443","22"], correct:"990"},
  {q:"Which port is SFTP?", options:["20","21","22","23"], correct:"22"},
  {q:"Which port is NetBIOS?", options:["137–139","443","3389","8080"], correct:"137–139"},
  {q:"Which port is DHCP?", options:["67/68","53","80","110"], correct:"67/68"},
  {q:"Which port is TFTP?", options:["21","69","80","443"], correct:"69"},
  {q:"Which port is NTP?", options:["53","123","161","389"], correct:"123"},
  
  {q:"Which connector is used to provide power to a SATA hard drive?", options:["SATA power","Molex","PCIe","Berg"], correct:"SATA power"},
  {q:"What is the maximum speed of USB 3.0?", options:["480 Mbps","5 Gbps","10 Gbps","20 Gbps"], correct:"5 Gbps"},
  {q:"Which component stores data permanently?", options:["RAM","CPU cache","SSD","Register"], correct:"SSD"},
  {q:"What type of cable is used for long-distance, high-speed networking?", options:["Coaxial","Fiber optic","Cat5e","Serial"], correct:"Fiber optic"},
  {q:"Which display connector is analog only?", options:["HDMI","DisplayPort","VGA","DVI-D"], correct:"VGA"},
  {q:"What does a UPS provide?", options:["Backup power","Cooling","Networking","Storage"], correct:"Backup power"},
  {q:"Which RAID level combines mirroring and striping?", options:["RAID 0","RAID 1","RAID 5","RAID 10"], correct:"RAID 10"},
  {q:"What is the purpose of a surge protector?", options:["Increase voltage","Prevent spikes","Boost signal","Store energy"], correct:"Prevent spikes"},
  {q:"Which port is commonly used for VGA connections?", options:["15-pin","9-pin","25-pin","8-pin"], correct:"15-pin"},

  {q:"A system powers on but no POST occurs. What is MOST likely?", options:["Bad RAM","Bad keyboard","Bad OS","Bad NIC"], correct:"Bad RAM"},
  {q:"A user hears clicking noises from a drive. What should be done?", options:["Ignore it","Replace drive","Defragment","Update BIOS"], correct:"Replace drive"},
  {q:"What tool is used to check cable continuity?", options:["Multimeter","Toner probe","Loopback plug","Cable tester"], correct:"Cable tester"},
  {q:"Which device regenerates signals on a network?", options:["Switch","Router","Repeater","Firewall"], correct:"Repeater"},
  {q:"What is the first step in troubleshooting?", options:["Identify problem","Test theory","Implement fix","Document"], correct:"Identify problem"},
  {q:"What is a loopback plug used for?", options:["Testing ports","Power supply","Cooling","Storage"], correct:"Testing ports"},
  {q:"A PC randomly reboots. What is MOST likely cause?", options:["Overheating","Keyboard issue","Mouse failure","Printer error"], correct:"Overheating"},
  {q:"What causes ghosting on a monitor?", options:["Slow refresh rate","Bad CPU","Bad RAM","Network lag"], correct:"Slow refresh rate"},
  {q:"What is the function of a toner probe?", options:["Locate cables","Measure voltage","Test RAM","Check ports"], correct:"Locate cables"},
  {q:"Which component is most affected by dust buildup?", options:["CPU fan","SSD","RAM","NIC"], correct:"CPU fan"},

  {q:"Which protocol sends email?", options:["SMTP","POP3","IMAP","DNS"], correct:"SMTP"},
  {q:"Which protocol retrieves email from a server (download and delete)?", options:["SMTP","FTP","POP3","SNMP"], correct:"POP3"},
  {q:"Which protocol allows email to remain on the server?", options:["SMTP","POP3","IMAP","DNS"], correct:"IMAP"},
  {q:"What does ICMP primarily do?", options:["File transfer","Error reporting","Email","DNS lookup"], correct:"Error reporting"},
  {q:"Which address is used for localhost?", options:["192.168.1.1","127.0.0.1","10.0.0.1","169.254.1.1"], correct:"127.0.0.1"},
  {q:"Which device connects different networks?", options:["Switch","Hub","Router","Repeater"], correct:"Router"},
  {q:"What does DHCP assign?", options:["MAC address","IP address","DNS record","Port"], correct:"IP address"},
  {q:"Which Wi-Fi encryption is considered deprecated and insecure?", options:["WEP","WPA2","WPA3","AES"], correct:"WEP"},
  {q:"What is packet loss?", options:["Lost data packets","Slow CPU","Bad RAM","Disk error"], correct:"Lost data packets"},
  {q:"What is jitter?", options:["Delay variation","Packet size","IP conflict","DNS issue"], correct:"Delay variation"},

  {q:"What type of IP is 10.0.0.0?", options:["Public","Private","Loopback","Multicast"], correct:"Private"},
  {q:"Which command displays active network connections?", options:["ping","ipconfig","netstat","tracert"], correct:"netstat"},
  {q:"Which command tests DNS resolution?", options:["nslookup","ping","netstat","route"], correct:"nslookup"},
  {q:"What is a firewall used for?", options:["Filtering traffic","Storing data","Speeding CPU","Cooling system"], correct:"Filtering traffic"},
  {q:"What is a proxy server?", options:["Intermediary server","Storage device","Firewall","Router"], correct:"Intermediary server"},
  {q:"Which topology uses a central connection point?", options:["Bus","Star","Ring","Mesh"], correct:"Star"},
  {q:"Which topology provides the most redundancy?", options:["Bus","Star","Mesh","Ring"], correct:"Mesh"},
  {q:"What is bandwidth?", options:["Maximum data capacity","Latency","Error rate","Voltage"], correct:"Maximum data capacity"},

  {q:"What is NFC primarily used for?", options:["Short-range communication","Wi-Fi networking","GPS tracking","Bluetooth audio"], correct:"Short-range communication"},
  {q:"What is remote wipe used for?", options:["Erase device data remotely","Restart device","Update OS","Lock screen"], correct:"Erase device data remotely"},
  {q:"Which feature disables all wireless radios on a phone?", options:["Airplane mode","Do Not Disturb","Hotspot","Bluetooth"], correct:"Airplane mode"},
  {q:"What is the main purpose of GPS on a mobile device?", options:["Location tracking","Networking","Storage","Encryption"], correct:"Location tracking"},
  {q:"Which mobile feature automatically locks a device after inactivity?", options:["Auto-lock","Encryption","VPN","Biometrics"], correct:"Auto-lock"},
  {q:"What is Bluetooth primarily used for?", options:["Short-range wireless communication","Internet routing","Cloud storage","GPS"], correct:"Short-range wireless communication"},

  {q:"What is a hypervisor responsible for?", options:["Managing virtual machines","Running applications","Providing storage","Encrypting data"], correct:"Managing virtual machines"},
  {q:"What is IaaS?", options:["Cloud infrastructure services","Software delivery","Platform tools","Networking only"], correct:"Cloud infrastructure services"},
  {q:"What is PaaS?", options:["Development platform in cloud","Infrastructure hardware","End-user software","Storage solution"], correct:"Development platform in cloud"},
  {q:"What is SaaS?", options:["Software delivered over internet","Hardware rental","Networking service","Security service"], correct:"Software delivered over internet"},
  {q:"What is cloud elasticity?", options:["Ability to scale resources","Encrypt data","Backup files","Route traffic"], correct:"Ability to scale resources"},
  {q:"What is a hybrid cloud?", options:["Combination of public and private cloud","Only private cloud","Only public cloud","Local-only cloud"], correct:"Combination of public and private cloud"},
  {q:"What is virtualization used for?", options:["Run multiple operating systems","Increase CPU speed","Add RAM","Cool hardware"], correct:"Run multiple operating systems"},
  {q:"What is a VM snapshot?", options:["Saved system state","Deleted VM","New OS install","Hardware reset"], correct:"Saved system state"},

  {q:"Which port is used by MySQL?", options:["1433","3306","1521","8080"], correct:"3306"},
  {q:"Which port is used by Oracle DB?", options:["1433","3306","1521","8080"], correct:"1521"},
  {q:"Which port is commonly used for HTTP alternate?", options:["8080","443","22","21"], correct:"8080"},
  {q:"Which port is used for Syslog?", options:["514","161","389","25"], correct:"514"},
  {q:"Which port is used by Kerberos?", options:["88","389","443","25"], correct:"88"},
  {q:"Which port is used for LDAPS?", options:["389","636","443","445"], correct:"636"},
  {q:"Which port is used for secure SMTP?", options:["25","465","110","143"], correct:"465"},
  {q:"Which port is used for secure IMAP?", options:["143","993","995","389"], correct:"993"},
  {q:"Which port is used for secure POP3?", options:["110","995","143","993"], correct:"995"}
];
